version: '3'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./notebooks:/home/jovyan/work  # Mount local directory "notebooks" to Jupyter container
      - ./data:/parquet_data  # Mount directory containing Parquet files to Jupyter container
    ports:
      - "8888:8888"  # Map container's port 8888 to host's port 8888